"""Add partial_fill flag to fuel details

Revision ID: 9004583311e5
Revises: d638966b4049
Create Date: 2026-08-24 09:51:52.462092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9004583311e5'
down_revision = 'd638966b4049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partial_fill', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_details', schema=None) as batch_op:
        batch_op.drop_column('partial_fill')

    # ### end Alembic commands ###
