"""Add tire expense type: TireDetail and TireSet

Revision ID: d638966b4049
Revises: c11b15bf9f66
Create Date: 2026-05-21 16:26:55.157554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd638966b4049'
down_revision = 'c11b15bf9f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tire_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('tire_type', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('dot_code', sa.String(length=10), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_expense_id', sa.Integer(), nullable=True),
    sa.Column('mounted', sa.Boolean(), nullable=True),
    sa.Column('mounted_at_odometer', sa.Integer(), nullable=True),
    sa.Column('total_km', sa.Integer(), nullable=True),
    sa.Column('max_age_months', sa.Integer(), nullable=True),
    sa.Column('max_km', sa.Integer(), nullable=True),
    sa.Column('notify_alerts', sa.Boolean(), nullable=True),
    sa.Column('age_alert_sent', sa.Boolean(), nullable=True),
    sa.Column('km_alert_sent', sa.Boolean(), nullable=True),
    sa.Column('retired', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['purchase_expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tire_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('tire_type', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('tire_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['tire_set_id'], ['tire_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tire_details')
    op.drop_table('tire_sets')
    # ### end Alembic commands ###
